//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Excursion.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Elementos
    {
        public string Nombre { get; set; }
        public Nullable<int> Calorias { get; set; }
        public Nullable<int> Peso { get; set; }
        public int IdElementos { get; set; }
    }
}
